---
abstract: 'Seamless database schema up- and downgrades'
author:
  - 'Sebastian Riedel, <kraihx@gmail.com>'
build_requires:
  DBD::Mock: '0'
  DBD::SQLite: '1.27'
  Test::API: '0'
  Test::DatabaseRow: '0'
  Test::Deep: '0'
  Test::Fatal: '0'
  Test::More: '1.001005'
  Test::Output: '0'
  Test::PostgreSQL: '0'
configure_requires:
  CPAN::Meta::Converter: '2.15001'
  CPAN::Meta::YAML: '0.02'
  JSON::PP: '4.16'
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4234, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBIx-Migration
provides:
  DBIx::Migration:
    file: lib/DBIx/Migration.pm
    version: '0.29'
  DBIx::Migration::CLI:
    file: lib/DBIx/Migration/CLI.pm
  DBIx::Migration::Pg:
    file: lib/DBIx/Migration/Pg.pm
recommends:
  Test::Needs: '0'
  Test::Pod: '1.26'
  Test::Pod::Coverage: '1.04'
  Text::Table::Tiny: '1.02'
requires:
  DBI: '1.33'
  File::Spec: '0'
  Log::Any: '1.044'
  Module::Load::Conditional: '0.6'
  Moo: '0'
  MooX::SetOnce: '0'
  MooX::StrictConstructor: '0'
  Path::Tiny: '0.062'
  PerlX::Maybe: '0'
  Pod::Find: '0'
  Pod::Usage: '2.05'
  String::Expand: '0'
  Try::Tiny: '0'
  Type::Tiny: '2.000001'
  Types::Path::Tiny: '0'
  Types::Self: '0'
  namespace::clean: '0'
  perl: v5.8.9
resources:
  bugtracker: https://github.com/XSven/perl-dbix-migration/issues
  license: http://dev.perl.org/licenses/
  repository: git://github.com/XSven/perl-dbix-migration.git
version: '0.29'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
